on:
  workflow_call:
    inputs:
      base-branch:
        description: >-
          The branch to use as the base for the PR.
        required: false
        type: string
        default: ''
      checkout-ref:
        description: >-
          The branch, tag or SHA to checkout.
        required: false
        type: string
      extra-args:
        description: >-
          Extra arguments to pass to pip-compile.
        required: false
        type: string
        default: ''
      path:
        description: >-
          The location of the requirement file(s).
        required: true
        type: string
      pr-auto-merge:
        description: >-
          Automatically merge only after necessary requirements are met.
        required: false
        type: string
        default: 'yes'
      pr-branch:
        description: >-
          The branch to use for the submitting the PR.
        type: string
        required: false
        default: 'coatl-dev-pip-compile-upgrade'
      pr-commit-message:
        description: >-
          Use the given <msg> as the commit message.
        required: false
        type: string
        default: 'chore(requirements): pip-compile upgrade'
      pr-delete-branch:
        description: >-
          Delete the local and remote branch after merge.
        required: false
        type: string
        default: 'no'
      sign-commits:
        required: false
        type: string
        default: 'yes'
      working-directory:
        description: >-
          The directory to run the workflow in.
        required: false
        type: string
        default: ${{ github.workspace }}
    secrets:
      gh-token:
        description: >-
          GitHub token.
        required: false
      gpg-sign-passphrase:
        description: >-
          GPG private key passphrase.
        required: false
      gpg-sign-private-key:
        description: >-
          GPG private key exported as an ASCII armored version.
        required: false

jobs:
  pip-compile-upgrade:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/coatl-dev/python-tools:2.7-pip-tools
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.checkout-ref }}
          persist-credentials: true

      - name: Upgrade requirements
        id: pip-compile-upgrade
        env:
          INPUT_PATH: ${{ inputs.path }}
          INPUT_EXTRA_ARGS: ${{ inputs.extra-args }}
        working-directory: ${{ inputs.working-directory }}
        run: |
          function process_file() {
            local file="$1"
            local extra_args="${INPUT_EXTRA_ARGS:-}"

            command=$(grep -m 1 "#    pip-compile" "$file")
            if [ -n "$command" ]; then
              upgrade_command=$(grep -m 1 "#    pip-compile" "$file" | sed "s/#    pip-compile/pip-compile --upgrade $extra_args/")
              eval "$upgrade_command"
            else
              exit 1
            fi
          }

          if [ -d "${INPUT_PATH}" ]; then
            cd "${INPUT_PATH}" || exit
            for file in *.txt; do
              if [ -f "$file" ]; then
                process_file "$file"
              fi
            done
          elif [ -f "${INPUT_PATH}" ]; then
            process_file "${INPUT_PATH}"
          else
            exit 1
          fi

      - name: Detect changes
        id: git-diff
        uses: coatl-dev/actions/simple-git-diff@a81a1c9a37205e630d28c561dfc3b605b6e031dd # v7.0.5
        with:
          path: ${{ inputs.path }}

      - name: Import GPG key
        if: ${{ steps.git-diff.outputs.diff == 'true' && inputs.sign-commits == 'yes' }}
        id: gpg-import
        uses: coatl-dev/actions/gpg-import@25b15c8e562e6c9e509bd29ea0b0da5ec6b26a1f # v7.0.4
        with:
          passphrase: ${{ secrets.gpg-sign-passphrase }}
          private-key: ${{ secrets.gpg-sign-private-key }}

      - name: Build commit message
        if: ${{ steps.git-diff.outputs.diff == 'true' }}
        run: |
          echo "${INPUTS_PR_COMMIT_MESSAGE}" > "$RUNNER_TEMP/commit.txt"
          {
              echo ""
              echo "updates:"
              git status --porcelain | awk 'match($1, "M") {print "  - " $2}'
          } >> "$RUNNER_TEMP/commit.txt"
        env:
          INPUTS_PR_COMMIT_MESSAGE: ${{ inputs.pr-commit-message }}

      - name: Commit and push changes
        if: ${{ steps.git-diff.outputs.diff == 'true' }}
        run: |
          git checkout -B ${INPUTS_PR_BRANCH}
          git add ${INPUTS_PATH}
          git commit --file="${RUNNER_TEMP}/commit.txt"
          git push --force --set-upstream origin ${INPUTS_PR_BRANCH}
        env:
          INPUTS_PR_BRANCH: ${{ inputs.pr-branch }}
          INPUTS_PATH: ${{ inputs.path }}

      - name: Create Pull Request
        if: ${{ steps.git-diff.outputs.diff == 'true' }}
        uses: coatl-dev/actions/pr-create@a81a1c9a37205e630d28c561dfc3b605b6e031dd # v7.0.5
        with:
          gh-token: ${{ secrets.gh-token }}
          auto-merge: ${{ inputs.pr-auto-merge }}
          base-branch: ${{ inputs.base-branch }}
          delete-branch: ${{ inputs.pr-delete-branch }}
