on:
  workflow_call:
    inputs:
      image:
        required: false
        type: string
        default: ubuntu-22.04
      python-version:
        required: false
        type: string
        default: "3.10"
      skip-hooks:
        required: false
        type: string
        default: ""

jobs:
  pre-commit:
    runs-on: ${{ inputs.image }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Set Python version
        run: |
          if '${{ startsWith(inputs.python-version, '2') }}'; then
            echo "PY=$(python --version 2>&1)" >> $GITHUB_ENV
          else
            echo "PY=$(python --version)" >> $GITHUB_ENV
          fi

      - name: Cache Python
        id: cache-python
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: py-${{ env.PY }}-${{ inputs.image }}
