on:
  workflow_call:
    inputs:
      cache:
        description: Whether to enable caching.
        required: false
        type: boolean
        default: true
      image:
        description: The type of machine to run the job on.
        required: false
        type: string
        default: ubuntu-latest
      python-version:
        description: Version of Python to use.
        required: false
        type: string
        default: '3.11'
      skip-hooks:
        required: false
        type: string
        default: ''
      timeout:
        description: >-
          The maximum number of minutes to let a job run before GitHub
          automatically cancels it.
        required: false
        type: number
        default: 15

jobs:
  pre-commit:
    runs-on: ${{ inputs.image }}
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache pip
        if: ${{ inputs.cache == true }}
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-pre-commit-${{ steps.setup-python.outputs.python-version }}-${{ inputs.image }}

      - name: Upgrade pre-installed dependencies
        run: |
          python -m pip install --upgrade \
            pip \
            setuptools \
            wheel

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pre-commit

      - name: Cache pre-commit
        if: ${{ inputs.cache == true }}
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ steps.setup-python.outputs.python-version }}-${{ inputs.image }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        env:
          SKIP: ${{ inputs.skip-hooks }}
        run: |
          pre-commit run --all-files --color=always
