on:
  workflow_call:
    inputs:
      skip-hooks:
        required: false
        type: string
        default: ''

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-pre-commit-${{ steps.setup-python.outputs.python-version }}-${{ runner.os }}

      - name: Upgrade pre-installed dependencies
        run: |
          python -m pip install --upgrade \
            pip \
            setuptools \
            wheel

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pre-commit

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ steps.setup-python.outputs.python-version }}-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        env:
          SKIP: ${{ inputs.skip-hooks }}
        run: |
          pre-commit run --all-files --color=always
