on:
  workflow_call:
    inputs:
      image:
        required: false
        type: string
        default: ubuntu-22.04
      python-version:
        required: false
        type: string
        default: "3.10"
      skip-hooks:
        required: false
        type: string
        default: ""

jobs:
  pre-commit:
    runs-on: ${{ inputs.image }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Set Python 2 version
        run: |
          echo "PY=$(python --version 2>&1)" >> $GITHUB_ENV
        if: startsWith('${{ inputs.python-version }}', '2')

      - name: Set Python 3 version
        run: |
          echo "PY=$(python --version)" >> $GITHUB_ENV
        if: startsWith('${{ inputs.python-version }}', '3')

      - name: Test PY
        run: |
          echo $PY
