on:
  workflow_call:
    inputs:
      checkout-ref:
        description: >-
          The branch, tag or SHA to checkout.
        required: false
        type: string
      skip-hooks:
        required: false
        type: string
        default: ''

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.checkout-ref }}
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        id: setup-python
        with:
          python-version: '3.14'

      - name: Checkout requirements repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: coatl-dev/workflow-requirements
          path: deps
          persist-credentials: false

      - name: Cache pip
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.cache/pip
          key: pip-${{ steps.setup-python.outputs.python-version }}-${{ runner.os }}-${{ hashFiles('deps/requirements/prek.txt') }}

      - name: Install requirements
        run: |
          python -m pip install --requirement deps/requirements/prek.txt

      - name: Cache prek
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.cache/prek
          key: prek-${{ steps.setup-python.outputs.python-version }}-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run prek
        env:
          SKIP: ${{ inputs.skip-hooks }}
        run: |
          prek run --all-files --color=always
