on:
  workflow_call:
    inputs:
      cache:
        description: Whether to enable caching.
        required: false
        type: boolean
        default: true
      image:
        description: The type of machine to run the job on.
        required: false
        type: string
        default: ubuntu-latest
      python-version:
        description: Version of Python to use.
        required: false
        type: string
        default: '3.11'
      timeout:
        description: >-
          The maximum number of minutes to let a job run before GitHub
          automatically cancels it.
        required: false
        type: number
        default: 15

jobs:
  pylint:
    runs-on: ${{ inputs.image }}
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache pip
        if: ${{ inputs.cache == true }}
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-pylint-${{ steps.setup-python.outputs.python-version }}-${{ inputs.image }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
