on:
  workflow_call:

jobs:
  pylint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-pylint-${{ steps.setup-python.outputs.python-version }}-${{ runner.os }}

      - name: Upgrade pre-installed dependencies
        run: |
          python -m pip install --upgrade \
            pip \
            setuptools \
            wheel

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
