on:
  workflow_call:

jobs:
  pylint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.11'

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: coatl-dev/workflow-requirements
          path: deps

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ steps.setup-python.outputs.python-version }}-${{ runner.os }}-${{ hashFiles('deps/requirements/base.txt', 'deps/requirements/pylint.txt') }}

      - name: Install requirements
        run: |
          python -m pip install --requirement deps/requirements/base.txt
          python -m pip install --requirement deps/requirements/pylint.txt

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
