on:
  workflow_call:
    inputs:
      checkout-ref:
        description: >-
          The branch, tag or SHA to checkout.
        required: false
        type: string
      path:
        description: >-
          This can be a module, package, directory or a file.
        required: false
        type: string
        default: ''
      extra-args:
        description: >-
          Extra arguments to pass to pylint.
        required: false
        type: string
        default: ''
      working-directory:
        description: >-
          The directory to run the workflow in.
        required: false
        type: string
        default: ${{ github.workspace }}

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Set up Python
        uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version: '3.14'

      - name: Checkout requirements repo
        uses: actions/checkout@v6
        with:
          repository: coatl-dev/workflow-requirements
          path: deps

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ steps.setup-python.outputs.python-version }}-${{ runner.os }}-${{ hashFiles('deps/requirements/pylint.txt') }}

      - name: Install requirements
        run: |
          python -m pip install --requirement deps/requirements/pylint.txt

      - name: Analysing the code with pylint
        working-directory: ${{ inputs.working-directory }}
        run: |
          if [ -z "${{ inputs.path }}" ]; then
            pylint ${{ inputs.extra-args }} $(git ls-files '*.py')
          else
            pylint ${{ inputs.extra-args }} ${{ inputs.path }}
          fi
