on:
  workflow_call:
    inputs:
      image:
        required: false
        type: string
        default: ubuntu-20.04
      python-version:
        required: false
        type: string
        default: "2.7"
    secrets:
      pypi-token:
        required: true

jobs:
  upload:
    runs-on: ${{ inputs.image }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache Python
        id: cache-python
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: py-${{ steps.setup-python.outputs.python-version }}-${{ inputs.image }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build package
        run: |
          python -m build

      - name: Check package with Twine
        run: |
          python -m twine check dist/*

      - name: Upload to PyPI via Twine
        env:
          TWINE_PASSWORD: ${{ secrets.pypi-token }}
        run: |
          python -m twine upload --verbose --username '__token__' dist/*
