on:
  workflow_call:
    inputs:
      python-version:
        description: Version of Python to use.
        required: false
        type: string
        default: '3.11'
      check:
        description: Check metadata with twine before uploading.
        required: false
        type: boolean
        default: true
      url:
        description: >-
          The repository (package index) URL to upload the package to.
        required: false
        type: string
        default: 'https://upload.pypi.org/legacy/'
      username:
        description: >-
          The username to authenticate to the repository (package index) as.
        required: false
        type: string
        default: '__token__'
    secrets:
      password:
        description: >-
          The password to authenticate to the repository (package index) with.
        required: true

jobs:
  upload:
    runs-on: ubuntu-22.04
    container:
      image: python:${{ inputs.python-version }}-slim
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: '1'
        PIP_NO_CACHE_DIR: '1'
        PIP_NO_PYTHON_VERSION_WARNING: '1'
        PIP_ROOT_USER_ACTION: 'ignore'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upgrade packages
        run: |
          python -m pip install --upgrade \
            pip \
            setuptools \
            wheel

      - name: Install dependencies
        run: |
          python -m pip install \
            build \
            twine

      - name: Build package
        run: |
          python -m build

      - name: Check package with Twine
        if: ${{ inputs.check }}
        run: |
          python -m twine check dist/*

      - name: Upload to PyPI via Twine
        env:
          TWINE_USERNAME: ${{ inputs.username }}
          TWINE_PASSWORD: ${{ secrets.password }}
          TWINE_REPOSITORY_URL: ${{ inputs.url }}
        run: |
          python -m twine upload --verbose dist/*
