on:
  workflow_call:
    inputs:
      checkout-ref:
        description: >-
          The branch, tag or SHA to checkout.
        required: false
        type: string
      python-version:
        description: Version of Python to use.
        required: false
        type: string
        default: '2.7'
      check:
        description: Check metadata with twine before uploading.
        required: false
        type: boolean
        default: true
      url:
        description: >-
          The repository (package index) URL to upload the package to.
        required: false
        type: string
        default: 'https://upload.pypi.org/legacy/'
      username:
        description: >-
          The username to authenticate to the repository (package index) as.
        required: false
        type: string
        default: '__token__'
      working-directory:
        description: >-
          The directory to run the workflow in.
        required: false
        type: string
        default: ${{ github.workspace }}
    secrets:
      password:
        description: >-
          The password to authenticate to the repository (package index) with.
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.checkout-ref }}
          persist-credentials: false

      - name: Upload Python package to PyPI
        uses: coatl-dev/actions/pypi-upload@40ccdf1f2742b1c19464d7997af84bbb249f89ca # v7.0.10
        with:
          python-version: ${{ inputs.python-version }}
          check: ${{ inputs.check }}
          url: ${{ inputs.url }}
          username: ${{ inputs.username }}
          password: ${{ secrets.password }}
          working-directory: ${{ inputs.working-directory }}
