on:
  workflow_call:
    inputs:
      python-version:
        description: >-
          Python version to use for installing pip-tools.
        required: false
        type: string
        default: '3.12'

jobs:
  tox:
    runs-on: ubuntu-22.04
    container: coatldev/six:${{ inputs.python-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upgrade pre-installed dependencies
        run: |
          python -m pip install --upgrade \
            pip \
            setuptools \
            wheel

      - name: Install dependencies
        run: |
          python -m pip install tox

      - name: Set PY
        run: |
          echo "PY=$(python --version | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache tox
        id: cache-tox
        uses: actions/cache@v4
        with:
          path: .tox
          key: tox-${{ env.PY }}-${{ runner.os }}-${{ hashFiles('tox.ini') }}

      - name: Run tests
        run: |
          tox
