on:
  workflow_call:
    inputs:
      checkout-ref:
        description: >-
          The branch, tag or SHA to checkout.
        required: false
        type: string
      extra-args:
        description: >-
          Extra arguments to pass to tox.
        required: false
        type: string
        default: ''
      working-directory:
        description: >-
          The working directory to run tox in.
        required: false
        type: string
        default: ${{ github.workspace }}
      uv-python:
        description: >-
          The Python version to use with uv.
        required: false
        type: string
        default: '3.14'

jobs:
  tox:
    runs-on: ubuntu-latest
    container:
      image: coatldev/six:latest # zizmor: ignore[unpinned-images]
      env:
        UV_PYTHON: ${{ inputs.uv-python }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.checkout-ref }}
          persist-credentials: false

      - name: Set up caching variables
        id: setup-caching
        run: |
          echo "uv-python=$(uvx python --version | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          if [[ "${INPUTS_WORKING_DIRECTORY}" != "${{ github.workspace }}" ]]; then
            echo "tox-cache-dir=${INPUTS_WORKING_DIRECTORY}/.tox" >> $GITHUB_OUTPUT
            echo "tox-ini=${INPUTS_WORKING_DIRECTORY}/tox.ini" >> $GITHUB_OUTPUT
          else
            echo "tox-cache-dir=.tox" >> $GITHUB_OUTPUT
            echo "tox-ini=tox.ini" >> $GITHUB_OUTPUT
          fi
        env:
          INPUTS_WORKING_DIRECTORY: ${{ inputs.working-directory }}

      - name: Cache tox
        id: cache-tox
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.setup-caching.outputs.tox-cache-dir }}
          key: tox-${{ steps.setup-caching.outputs.uv-python }}-${{ runner.os }}-${{ hashFiles(steps.setup-caching.outputs.tox-ini) }}

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: |
          uvx tox ${INPUTS_EXTRA_ARGS}
        env:
          INPUTS_EXTRA_ARGS: ${{ inputs.extra-args }}
