on:
  workflow_call:
    inputs:
      image:
        description: The type of machine to run the job on.
        required: false
        type: string
        default: ubuntu-latest
      timeout:
        description: >-
          The maximum number of minutes to let a job run before GitHub
          automatically cancels it.
        required: false
        type: number
        default: 15

jobs:
  tox:
    runs-on: ${{ inputs.image }}
    container: coatldev/six:3.11
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Ref: https://github.com/actions/runner/issues/652
      - name: Install dependencies (with no caching)
        run: |
          python -m pip install --no-cache-dir --upgrade pip tox

      - name: Set PY
        run: |
          echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache tox
        id: cache-tox
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-${{ env.PY }}-${{ inputs.image }}-${{ hashFiles('tox.ini') }}

      - name: Run tests
        run: |
          tox
