on:
  workflow_call:
    inputs:
      cache:
        description: Whether to enable caching.
        required: false
        type: boolean
        default: true
      image:
        description: The type of machine to run the job on.
        required: false
        type: string
        default: ubuntu-latest
      timeout:
        description: >-
          The maximum number of minutes to let a job run before GitHub
          automatically cancels it.
        required: false
        type: number
        default: 15

jobs:
  tox:
    runs-on: ${{ inputs.image }}
    container: coatldev/six:3.11
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upgrade pre-installed dependencies
        run: |
          python -m pip install --upgrade \
            pip \
            setuptools \
            wheel

      - name: Install dependencies
        run: |
          python -m pip install tox

      - name: Set PY
        run: |
          echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache tox
        if: ${{ inputs.cache == true }}
        id: cache-tox
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-${{ env.PY }}-${{ inputs.image }}-${{ hashFiles('tox.ini') }}

      - name: Run tests
        run: |
          tox
