on:
  workflow_call:
    inputs:
      checkout-ref:
        description: >-
          The branch, tag or SHA to checkout.
        required: false
        type: string
      python-versions:
        description: >-
          Version range or exact version of Python to use, using SemVer's version range syntax.
        required: true
        type: string
      extra-args:
        description: >-
          Extra arguments to pass to tox.
        required: false
        type: string
        default: ''
      working-directory:
        description: >-
          The working directory to run tox in.
        required: false
        type: string
        default: ${{ github.workspace }}

jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.checkout-ref }}
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        id: setup-python
        with:
          python-version: '3.14'

      - name: Checkout requirements repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: coatl-dev/workflow-requirements
          path: deps
          persist-credentials: false

      - name: Cache pip
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/pip
          key: pip-${{ steps.setup-python.outputs.python-version }}-${{ runner.os }}-${{ hashFiles('deps/requirements/tox.txt') }}

      - name: Install requirements
        run: |
          python -m pip install --requirement deps/requirements/tox.txt

      - name: Set up tox caching
        id: setup-tox
        run: |
          if [[ "${INPUTS_WORKING_DIRECTORY}" != "${{ github.workspace }}" ]]; then
            echo "tox-cache-dir=${INPUTS_WORKING_DIRECTORY}/.tox" >> $GITHUB_OUTPUT
            echo "tox-ini=${INPUTS_WORKING_DIRECTORY}/tox.ini" >> $GITHUB_OUTPUT
          else
            echo "tox-cache-dir=.tox" >> $GITHUB_OUTPUT
            echo "tox-ini=tox.ini" >> $GITHUB_OUTPUT
          fi
        env:
          INPUTS_WORKING_DIRECTORY: ${{ inputs.working-directory }}

      - name: Cache tox
        id: cache-tox
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.setup-tox.outputs.tox-cache-dir }}
          key: tox-${{ steps.setup-python.outputs.python-version }}-${{ runner.os }}-${{ hashFiles(steps.setup-tox.outputs.tox-ini) }}

      - name: Set up Python versions for tox
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ inputs.python-versions }}

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: |
          tox ${INPUTS_EXTRA_ARGS}
        env:
          INPUTS_EXTRA_ARGS: ${{ inputs.extra-args }}
