on:
  workflow_call:

jobs:
  tox:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.11'

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: coatl-dev/workflow-requirements
          path: coatl-dev/requirements

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ steps.setup-python.outputs.python-version }}-${{ runner.os }}-${{ hashFiles('coatl-dev/requirements/tox/requirements.txt') }}

      - name: Install requirements
        run: |
          python -m pip install --requirement coatl-dev/requirements/tox/requirements.txt

      - name: Cache tox
        id: cache-tox
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-${{ steps.setup-python.outputs.python-version }}-${{ runner.os }}-${{ hashFiles('tox.ini') }}

      - name: Run tests
        run: |
          tox
