on:
  workflow_call:
    inputs:
      base-branch:
        description: >-
          The branch to use as the base for the PR.
        required: false
        type: string
        default: ''
      checkout-ref:
        description: >-
          The branch, tag or SHA to checkout.
        required: false
        type: string
      path:
        description: >-
          The location of the requirement file(s).
        required: true
        type: string
      pr-auto-merge:
        description: >-
          Automatically merge only after necessary requirements are met.
        required: false
        type: string
        default: 'yes'
      pr-branch:
        description: >-
          The branch to use for the submitting the PR.
        type: string
        required: false
        default: 'coatl-dev-pip-compile-upgrade'
      pr-commit-message:
        description: >-
          Use the given <msg> as the commit message.
        required: false
        type: string
        default: 'chore(requirements): uv pip compile upgrade'
      pr-delete-branch:
        description: >-
          Delete the local and remote branch after merge.
        required: false
        type: string
        default: 'no'
      python-version:
        description: >-
          The version of Python to set UV_PYTHON to.
        required: false
        type: string
        default: '3.14'
      sign-commits:
        required: false
        type: string
        default: 'yes'
      working-directory:
        description: >-
          The directory to run the workflow in.
        required: false
        type: string
        default: ${{ github.workspace }}
    secrets:
      gh-token:
        description: >-
          GitHub token.
        required: false
      gpg-sign-passphrase:
        description: >-
          GPG private key passphrase.
        required: false
      gpg-sign-private-key:
        description: >-
          GPG private key exported as an ASCII armored version.
        required: false


jobs:
  pip-compile-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.checkout-ref }}
          persist-credentials: true

      - name: Update requirements
        id: pip-compile
        uses: coatl-dev/actions/uv-pip-compile-upgrade@964d16d81f03cdd4e1ff713d142d48d074f7e1ac # v7.0.15
        with:
          path: ${{ inputs.path }}
          python-version: '${{ inputs.python-version }}'
          working-directory: ${{ inputs.working-directory }}

      - name: Detect changes
        id: git-diff
        uses: coatl-dev/actions/simple-git-diff@964d16d81f03cdd4e1ff713d142d48d074f7e1ac # v7.0.15
        with:
          path: ${{ inputs.path }}

      - name: Import GPG key
        if: ${{ steps.git-diff.outputs.diff == 'true' && inputs.sign-commits == 'yes' }}
        id: gpg-import
        uses: coatl-dev/actions/gpg-import@964d16d81f03cdd4e1ff713d142d48d074f7e1ac # v7.0.15
        with:
          passphrase: ${{ secrets.gpg-sign-passphrase }}
          private-key: ${{ secrets.gpg-sign-private-key }}

      - name: Build commit message
        if: ${{ steps.git-diff.outputs.diff == 'true' }}
        run: |
          echo "${INPUTS_PR_COMMIT_MESSAGE}" > "$RUNNER_TEMP/commit.txt"
          {
              echo ""
              echo "updates:"
              git status --porcelain | awk 'match($1, "M") {print "  - " $2}'
          } >> "$RUNNER_TEMP/commit.txt"
        env:
          INPUTS_PR_COMMIT_MESSAGE: ${{ inputs.pr-commit-message }}

      - name: Commit and push changes
        if: ${{ steps.git-diff.outputs.diff == 'true' }}
        run: |
          git checkout -B ${INPUTS_PR_BRANCH}
          git add ${INPUTS_PATH}
          git commit --file="${RUNNER_TEMP}/commit.txt"
          git push --force --set-upstream origin ${INPUTS_PR_BRANCH}
        env:
          INPUTS_PR_BRANCH: ${{ inputs.pr-branch }}
          INPUTS_PATH: ${{ inputs.path }}

      - name: Create Pull Request
        if: ${{ steps.git-diff.outputs.diff == 'true' }}
        uses: coatl-dev/actions/pr-create@964d16d81f03cdd4e1ff713d142d48d074f7e1ac # v7.0.15
        with:
          gh-token: ${{ secrets.gh-token }}
          auto-merge: ${{ inputs.pr-auto-merge }}
          base-branch: ${{ inputs.base-branch }}
          delete-branch: ${{ inputs.pr-delete-branch }}
